### ISSUE TITLE
`xargs: illegal option`

### ISSUE THREAD

**Issue by vict0rsch** [KulkarniKaustubh/fzf-dir-navigator#2]
I'm seeing the right panel error ; is this expected?

```
$ fzf --version
0.42.0 (brew)

$ zsh --version
zsh 5.9 (x86_64-apple-darwin22.0)
```

<img width="1291" alt="SCR-20230701-kdcv" src="https://github.com/KulkarniKaustubh/fzf-dir-navigator/assets/9283470/b0c39a0f-a1f4-4ace-94d9-4da34d4fbdee">

**Comment by KulkarniKaustubh** [comment]
Hey, this is due to macOS having a different `xargs` command than Linux. The latest commit should have fixed this now, please try it out and let me know. If it works, do close the issue!

Thanks and cheers!

**Comment by vict0rsch** [comment]
Fixed, thanks a lot!!
