### ISSUE TITLE
Make `fzf-dir-navigator` use `.zhistory`

### ISSUE THREAD

**Issue by vict0rsch** [KulkarniKaustubh/fzf-dir-navigator#3]
Not sure if this is this project's goal, but it could be great to have an option to search in the history of `z` instead of the file system. That could greatly speed up search, especially in very deep folders (like `~`)

**Comment by KulkarniKaustubh** [comment]
I think that this can easily be done with a <kbd>ctrl-r</kbd> on the terminal (using the recursive search and searching for the directory that was previously `cd`'d into). This plugin also shows a recent history of directories that were navigated to. It is kind of a mini history in itself that can be used to quickly go to previously visited directories. (I personally use this A LOT :smile:)

Please let me know if I have misunderstood what you were asking for. Thanks!

**Comment by vict0rsch** [comment]
well the issue is that it would help _prioritize_ results too so that there's no fussy-matched junk that shows up before where I actually want to go
