### ISSUE TITLE
Permissions in Macos

### ISSUE THREAD

**Issue by bdahan** [KulkarniKaustubh/fzf-dir-navigator#5]
Hi,
Thanks for the plugin. can you elaborate more one this section:

> Access must be given to access folders on the system since the tool searches for all directories in /Users/<username/

when ctrl f I see the search windows but no folders showing there.

Thanks,

**Comment by KulkarniKaustubh** [comment]
Hey @bdahan,

https://support.apple.com/en-in/guide/mac-help/mchld5a35146/mac

This link should help! You need to provide your terminal access to all files and folders on your system. Hope this works!

**Comment by bdahan** [comment]
Thank you, it worked 👍

**Comment by KulkarniKaustubh** [comment]
Okay, glad to hear! Closing the issue.
