### ISSUE TITLE
Suggestion: Make files selectable

### ISSUE THREAD

**Issue by aemonge** [KulkarniKaustubh/fzf-dir-navigator#6]
Would be great to use this to select files to, like `vim <c-f>` and select the file

**Comment by KulkarniKaustubh** [comment]
Hey! Although this is not in the scope for this project, there is a way you can do it with the default [fzf keybindings](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh). So, you can type out `vim` and hit `C-t` to search for the file you want to edit on your system. Once you fuzzy find the file, you can hit enter and start editing. You would need to source the keybindings file in your `.zshrc` for this to work.

Hope this works for you! Cheers!
